server:
  port: ${SERVER_PORT:8080}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN:7956376741:AAEEswT9TPpkYn5FSBSEpCMqrGgLA560J4w}
    username: ${TELEGRAM_BOT_USERNAME:Ticketero14_amazonQ_Bot}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.banco.ticketero: INFO
    org.telegram: WARN

ticketero:
  scheduler:
    cancel-expired:
      enabled: true
      fixed-delay: 60000  # 60 segundos
    notifications:
      enabled: true
      fixed-delay: 30000  # 30 segundos
  queue-config:
    caja:
      vigencia-minutos: 60
    personal-banker:
      vigencia-minutos: 120
    empresas:
      vigencia-minutos: 180
    gerencia:
      vigencia-minutos: 240